# Ghidra applier: push the verified source's types/signatures/learnings onto the
# loaded original program, keyed by mangled symbol name (resolved via Ghidra's own
# symbol table -- no _work/ files). Idempotent; safe to re-run after editing the data.
#
# Run from Ghidra's Script Manager, or via the MCP `run_ghidra_script apply_source.py`
# once GHIDRA_MCP_ALLOW_SCRIPTS=1 is set. Inputs (sibling files, repo-tracked):
#   source_types.json   -- generated by export_source_types.py from the -g DWARF build
#   learnings.json       -- curated structural comments
#
# Phases (args, space-separated; default "structs globals comments"):
#   structs globals comments protos     -- "protos" (all ~5.5k prototypes) is slow/opt-in
#@category GOF2
import json
import os

from ghidra.program.model.data import (
    ArrayDataType, BooleanDataType, CategoryPath, CharDataType, DataTypeConflictHandler,
    DoubleDataType, FloatDataType, IntegerDataType, LongLongDataType, PointerDataType,
    ShortDataType, SignedCharDataType, StructureDataType, Undefined1DataType,
    UnsignedIntegerDataType, UnsignedLongLongDataType, UnsignedShortDataType, VoidDataType,
)
from ghidra.program.model.listing import CodeUnit, ParameterImpl
from ghidra.program.model.symbol import SourceType

# Data (source_types.json / learnings.json) lives in the repo; the .py is copied into
# Ghidra's script path (~/ghidra_scripts), where __file__ is not the repo -- so pin it.
HERE = "/Users/fionera/Downloads/GalaxyOnFire2/gof2-decomp/tools/ghidra"
DTM = currentProgram.getDataTypeManager()
ST = currentProgram.getSymbolTable()
FM = currentProgram.getFunctionManager()
LST = currentProgram.getListing()
LOG = {"struct_resized": [], "type_unresolved": {}, "sym_missing": 0, "applied": {}}

PRIM = {
    "void": VoidDataType.dataType, "bool": BooleanDataType.dataType,
    "char": CharDataType.dataType, "signed char": SignedCharDataType.dataType,
    "unsigned char": Undefined1DataType.dataType, "short": ShortDataType.dataType,
    "unsigned short": UnsignedShortDataType.dataType, "int": IntegerDataType.dataType,
    "unsigned int": UnsignedIntegerDataType.dataType, "long long": LongLongDataType.dataType,
    "unsigned long long": UnsignedLongLongDataType.dataType,
    "float": FloatDataType.dataType, "double": DoubleDataType.dataType,
}


def find_named(name):
    """First existing Ghidra DataType with this (simple) name, any category."""
    out = java_list()
    DTM.findDataTypes(name, out)
    return out.get(0) if out.size() > 0 else None


def java_list():
    from java.util import ArrayList
    return ArrayList()


def resolve_type(s):
    s = s.strip()
    if s.endswith("*"):
        return PointerDataType(resolve_type(s[:-1]))
    if s.endswith("]"):
        base, _, n = s[:-1].rpartition("[")
        elem = resolve_type(base)
        try:
            cnt = int(n)
        except ValueError:
            cnt = 0
        return ArrayDataType(elem, max(cnt, 1), elem.getLength())
    if s in PRIM:
        return PRIM[s]
    dt = find_named(s)
    if dt is not None:
        return dt
    LOG["type_unresolved"][s] = LOG["type_unresolved"].get(s, 0) + 1
    return Undefined1DataType.dataType  # never crash; placeholder


def existing_names_by_offset(name):
    """Map offset -> field name for the current Ghidra struct (to preserve good names)."""
    dt = find_named(name)
    out = {}
    if dt is not None and hasattr(dt, "getComponents"):
        for c in dt.getComponents():
            fn = c.getFieldName()
            if fn and not fn.startswith("field_") and not fn.startswith("unnamed"):
                out[c.getOffset()] = fn
    return out


def apply_structs(data, force=False):
    # Safety: some Ghidra structs are already richer than / structurally different from
    # the source (e.g. Transform: raw fields + names like flRotation/boundingCenter, and
    # a different model). Blindly overwriting would REGRESS them. Default: only fix structs
    # that are stale (size differs) or where Ghidra has fewer real names than the source.
    # Pass force=True to overwrite everything. Every decision is logged.
    keep = {}  # preserved Ghidra names per struct
    for name, info in data.items():
        try:
            old = find_named(name)
            keep[name] = existing_names_by_offset(name)
            if old is not None and not force:
                size_ok = old.getLength() == int(info["size"])
                src_named = sum(1 for m in info["members"]
                                if not m["name"].startswith("field_0x"))
                if size_ok and len(keep[name]) >= src_named:
                    LOG.setdefault("struct_kept", []).append(name)  # Ghidra >= source: keep
                    continue
            cat = old.getCategoryPath() if old is not None else CategoryPath("/GOF2")
            st = StructureDataType(cat, name, int(info["size"]), DTM)
            if old is not None and old.getLength() != int(info["size"]):
                LOG["struct_resized"].append("%s %d->%d" % (name, old.getLength(), info["size"]))
            for m in info["members"]:
                off, mname = int(m["offset"]), m["name"]
                if mname.startswith("field_0x") and off in keep[name]:
                    mname = keep[name][off]  # preserve a better existing Ghidra name
                dt = resolve_type(m["type"])
                if off + dt.getLength() <= st.getLength():
                    st.replaceAtOffset(off, dt, dt.getLength(), mname, None)
            DTM.addDataType(st, DataTypeConflictHandler.REPLACE_HANDLER)
            LOG["applied"]["structs"] = LOG["applied"].get("structs", 0) + 1
        except Exception as e:
            println("[struct] %s: %s" % (name, e))


def addr_of(mangled):
    syms = ST.getSymbols(mangled)
    for s in syms:
        return s.getAddress()
    return None


def apply_globals(data):
    for mangled, tstr in data.items():
        try:
            a = addr_of(mangled)
            if a is None:
                LOG["sym_missing"] += 1
                continue
            dt = resolve_type(tstr)
            try:
                LST.clearCodeUnits(a, a.add(max(dt.getLength() - 1, 0)), False)
            except Exception:
                pass
            DTM_create_data(a, dt)
            LOG["applied"]["globals"] = LOG["applied"].get("globals", 0) + 1
        except Exception as e:
            println("[global] %s: %s" % (mangled, e))


def DTM_create_data(addr, dt):
    try:
        LST.createData(addr, dt)
    except Exception:
        pass  # already typed / conflict -- leave it


def apply_protos(data):
    n = 0
    for mangled, sig in data.items():
        a = addr_of(mangled)
        if a is None:
            LOG["sym_missing"] += 1
            continue
        fn = FM.getFunctionAt(a)
        if fn is None:
            continue
        try:
            params = []
            for p in sig["params"]:
                if p["type"] == "...":
                    continue
                pn = p["name"] or None
                params.append(ParameterImpl(pn, resolve_type(p["type"]), currentProgram))
            from ghidra.program.model.listing.Function import FunctionUpdateType
            fn.replaceParameters(params, FunctionUpdateType.DYNAMIC_STORAGE_ALL_PARAMS,
                                 True, SourceType.USER_DEFINED)
            fn.setReturnType(resolve_type(sig["ret"]), SourceType.USER_DEFINED)
            n += 1
            if n % 500 == 0:
                println("  ...protos %d" % n)
        except Exception as e:
            if n < 20:
                println("[proto] %s: %s" % (mangled, e))
    LOG["applied"]["protos"] = n


def apply_comments(learn):
    for tname, txt in learn.get("types", {}).items():
        dt = find_named(tname)
        if dt is not None:
            try:
                dt.setDescription(txt)
                LOG["applied"]["type_comments"] = LOG["applied"].get("type_comments", 0) + 1
            except Exception as e:
                println("[type-comment] %s: %s" % (tname, e))
    for mangled, txt in learn.get("symbols", {}).items():
        a = addr_of(mangled)
        if a is None:
            continue
        try:
            LST.setComment(a, CodeUnit.PLATE_COMMENT, txt)
            LOG["applied"]["sym_comments"] = LOG["applied"].get("sym_comments", 0) + 1
        except Exception as e:
            println("[sym-comment] %s: %s" % (mangled, e))


def main():
    args = getScriptArgs()
    phases = list(args) if args else ["structs", "globals", "comments"]
    src = json.load(open(os.path.join(HERE, "source_types.json")))
    learn = json.load(open(os.path.join(HERE, "learnings.json")))
    tx = currentProgram.startTransaction("apply_source")
    try:
        if "structs" in phases:
            println("== structs =="); apply_structs(src["structs"], force=("force" in phases))
        if "globals" in phases:
            println("== globals =="); apply_globals(src["globals"])
        if "comments" in phases:
            println("== comments =="); apply_comments(learn)
        if "protos" in phases:
            println("== protos (slow) =="); apply_protos(src["functions"])
    finally:
        currentProgram.endTransaction(tx, True)
    println("APPLIED: %s" % LOG["applied"])
    println("structs kept (Ghidra already >= source): %d" % len(LOG.get("struct_kept", [])))
    println("struct resizes: %s" % LOG["struct_resized"])
    println("symbols missing in program: %d" % LOG["sym_missing"])
    top = sorted(LOG["type_unresolved"].items(), key=lambda kv: -kv[1])[:15]
    println("top unresolved types: %s" % top)


main()
