// AUTO-GENERATED by work/gen_consts.py — real values for const data-table stubs,
// extracted from the target's .rodata/.data. Overrides the zeroed weak stubs.
// (g_MiningGame_layerTableRender dropped: unaligned address = misresolution; recover reactively.)
#include <stdint.h>

extern "C" uint32_t Standing_enemyRaceTable[4];
uint32_t Standing_enemyRaceTable[4] = { 1, 0, 3, 2 };

extern "C" int gGDS_pairTable[];
int gGDS_pairTable[] = { 679, 667, 673, 674, 675, 676, 677, 678, 661, 668, 669, 670, 671, 672, 662, 663 };

extern "C" int* gRaceTable;
static const int _d_gRaceTable[] = { 3, 0, 8, 3, 2, 0, 3, 0, 9, 1, 0, 8, 2, 0, 0, 0 };
int* gRaceTable = (int*)_d_gRaceTable;

extern "C" int kAttackRaceTable[4];
int kAttackRaceTable[4] = { 1, 0, 3, 2 };
