// AUTO-GENERATED by work/gen_vtables.py — real vtables for the *vtable* stub symbols.
// Each array reproduces the target's .data.rel.ro vtable (Itanium layout); each stub var
// holds the array base so the engine's `(char*)stub + 8` yields the correct vptr.

extern "C" {
  void vfn_0() asm("_ZTI7BeamGun");
  void vfn_1() asm("_ZN7BeamGunD2Ev");
  void vfn_10() asm("_ZN11AbstractGun9isBombGunEv");
  void vfn_100() asm("_ZN14PlayerAsteroid19getProjectionVectorERKN11AbyssEngine6AEMath6VectorE");
  void vfn_101() asm("_ZN8KIPlayer18getCollisionNormalERKN11AbyssEngine6AEMath6VectorE");
  void vfn_102() asm("_ZN8KIPlayer25projectCollisionOnSurfaceERKN11AbyssEngine6AEMath6VectorE");
  void vfn_103() asm("_ZN8KIPlayer8setStateEi");
  void vfn_104() asm("_ZTI13PlayerStation");
  void vfn_105() asm("_ZN13PlayerStationD2Ev");
  void vfn_106() asm("_ZN13PlayerStationD0Ev");
  void vfn_107() asm("_ZN12PlayerStatic9translateERKN11AbyssEngine6AEMath6VectorE");
  void vfn_108() asm("_ZN13PlayerStation6renderEv");
  void vfn_109() asm("_ZN13PlayerStation11getPositionEv");
  void vfn_11() asm("_ZN11AbstractGun9isMineGunEv");
  void vfn_110() asm("_ZN8KIPlayer8initPushERKN11AbyssEngine6AEMath6VectorEi");
  void vfn_111() asm("_ZN8KIPlayer4pushEi");
  void vfn_112() asm("_ZN13PlayerStation6updateEi");
  void vfn_113() asm("_ZN13PlayerStation7collideEfff");
  void vfn_114() asm("_ZN13PlayerStation12outerCollideEfff");
  void vfn_115() asm("_ZN13PlayerStation12outerCollideERKN11AbyssEngine6AEMath6VectorE");
  void vfn_116() asm("_ZN13PlayerStation11setPositionERKN11AbyssEngine6AEMath6VectorE");
  void vfn_117() asm("_ZN13PlayerStation19getProjectionVectorERKN11AbyssEngine6AEMath6VectorE");
  void vfn_118() asm("_ZN13PlayerStation25projectCollisionOnSurfaceERKN11AbyssEngine6AEMath6VectorE");
  void vfn_119() asm("_ZTI9RocketGun");
  void vfn_12() asm("_ZN11AbstractGun12isAutoTurretEv");
  void vfn_120() asm("_ZN9RocketGunD2Ev");
  void vfn_121() asm("_ZN9RocketGunD0Ev");
  void vfn_122() asm("_ZN9RocketGun6updateEi");
  void vfn_123() asm("_ZN9RocketGun6renderEv");
  void vfn_124() asm("_ZTI8Waypoint");
  void vfn_125() asm("_ZN8WaypointD2Ev");
  void vfn_126() asm("_ZN8WaypointD0Ev");
  void vfn_127() asm("_ZN8KIPlayer9translateERKN11AbyssEngine6AEMath6VectorE");
  void vfn_128() asm("_ZN8KIPlayer6renderEv");
  void vfn_129() asm("_ZN8Waypoint11getPositionEv");
  void vfn_13() asm("_ZTI7BombGun");
  void vfn_130() asm("_ZN8KIPlayer6updateEi");
  void vfn_131() asm("_ZN8KIPlayer7collideEfff");
  void vfn_132() asm("_ZN8KIPlayer12outerCollideEfff");
  void vfn_133() asm("_ZN8KIPlayer11setPositionERKN11AbyssEngine6AEMath6VectorE");
  void vfn_134() asm("_ZN8KIPlayer19getProjectionVectorERKN11AbyssEngine6AEMath6VectorE");
  void vfn_135() asm("_ZTI20FileInterfaceAndroid");
  void vfn_136() asm("_ZN20FileInterfaceAndroidD2Ev");
  void vfn_137() asm("_ZN20FileInterfaceAndroidD0Ev");
  void vfn_138() asm("_ZN20FileInterfaceAndroid8OpenReadEN11AbyssEngine6StringEibiij");
  void vfn_139() asm("_ZN20FileInterfaceAndroid9OpenWriteEN11AbyssEngine6StringEibj");
  void vfn_14() asm("_ZN7BombGunD2Ev");
  void vfn_140() asm("_ZN20FileInterfaceAndroid10OpenAppendEN11AbyssEngine6StringEibj");
  void vfn_141() asm("_ZN20FileInterfaceAndroid4ReadEjPv");
  void vfn_142() asm("_ZN20FileInterfaceAndroid5WriteEjPKv");
  void vfn_143() asm("_ZN20FileInterfaceAndroid4SeekEj");
  void vfn_144() asm("_ZN20FileInterfaceAndroid11GetFileSizeEv");
  void vfn_145() asm("_ZN20FileInterfaceAndroid9FileExistEN11AbyssEngine6StringE");
  void vfn_146() asm("_ZN20FileInterfaceAndroid10FileDeleteEN11AbyssEngine6StringE");
  void vfn_147() asm("_ZN20FileInterfaceAndroid18GetDeviceFreeSpaceEv");
  void vfn_148() asm("_ZN20FileInterfaceAndroid13GetAppRootDirEv");
  void vfn_149() asm("_ZN20FileInterfaceAndroid13SetAppRootDirEPv");
  void vfn_15() asm("_ZN7BombGunD0Ev");
  void vfn_150() asm("_ZN20FileInterfaceAndroid15SetZipDirectoryEPv");
  void vfn_151() asm("_ZN20FileInterfaceAndroid12FileEnumInitEPcb");
  void vfn_152() asm("_ZN20FileInterfaceAndroid15FileGetNextEnumERN11AbyssEngine6StringE");
  void vfn_153() asm("_ZN20FileInterfaceAndroid5CloseEv");
  void vfn_154() asm("_ZN20FileInterfaceAndroid12GetDirPreFixEv");
  void vfn_155() asm("_ZN20FileInterfaceAndroid6OutputEPc");
  void vfn_156() asm("_ZN20FileInterfaceAndroid16SetSaveDirectoryEN11AbyssEngine6StringE");
  void vfn_157() asm("_ZN20FileInterfaceAndroid18ResetSaveDirectoryEv");
  void vfn_158() asm("_ZTI13PlayerFighter");
  void vfn_159() asm("_ZN13PlayerFighterD2Ev");
  void vfn_16() asm("_ZN9ObjectGun10setEnemiesEP5ArrayIP6PlayerE");
  void vfn_160() asm("_ZN13PlayerFighterD0Ev");
  void vfn_161() asm("_ZN13PlayerFighter12setShipGroupEP10AEGeometryib");
  void vfn_162() asm("_ZN13PlayerFighter5awakeEv");
  void vfn_163() asm("_ZN13PlayerFighter17setWingmanCommandEiP8KIPlayer");
  void vfn_164() asm("_ZN13PlayerFighter8setLevelEP5Level");
  void vfn_165() asm("_ZN13PlayerFighter6reviveEv");
  void vfn_166() asm("_ZN13PlayerFighter8setSpeedEf");
  void vfn_167() asm("_ZN13PlayerFighter6renderEv");
  void vfn_168() asm("_ZN8KIPlayer11getPositionEv");
  void vfn_169() asm("_ZN13PlayerFighter8initPushERKN11AbyssEngine6AEMath6VectorEi");
  void vfn_17() asm("_ZN9ObjectGun8setEnemyEP6Player");
  void vfn_170() asm("_ZN13PlayerFighter4pushEi");
  void vfn_171() asm("_ZN13PlayerFighter6updateEi");
  void vfn_172() asm("_ZN13PlayerFighter7collideEfff");
  void vfn_173() asm("_ZN13PlayerFighter12outerCollideEfff");
  void vfn_174() asm("_ZN13PlayerFighter11setPositionERKN11AbyssEngine6AEMath6VectorE");
  void vfn_175() asm("_ZN13PlayerFighter11setPositionEfff");
  void vfn_176() asm("_ZTI12PlayerTurret");
  void vfn_177() asm("_ZN12PlayerTurretD2Ev");
  void vfn_178() asm("_ZN12PlayerTurretD0Ev");
  void vfn_179() asm("_ZN12PlayerTurret8setLevelEP5Level");
  void vfn_18() asm("_ZN7BombGun6updateEi");
  void vfn_180() asm("_ZN12PlayerTurret6reviveEv");
  void vfn_181() asm("_ZN12PlayerTurret6renderEv");
  void vfn_182() asm("_ZN12PlayerTurret6updateEi");
  void vfn_183() asm("_ZN12PlayerTurret7collideEfff");
  void vfn_184() asm("_ZN12PlayerTurret12outerCollideEfff");
  void vfn_185() asm("_ZN12PlayerTurret11setPositionERKN11AbyssEngine6AEMath6VectorE");
  void vfn_186() asm("_ZTI12AENormalFile");
  void vfn_187() asm("_ZN12AENormalFileD2Ev");
  void vfn_188() asm("_ZN12AENormalFileD0Ev");
  void vfn_189() asm("_ZN12AENormalFile5WriteEjPv");
  void vfn_19() asm("_ZN7BombGun6renderEv");
  void vfn_190() asm("_ZN12AENormalFile4ReadEjPv");
  void vfn_191() asm("_ZN12AENormalFile4SkipEj");
  void vfn_192() asm("_ZN12AENormalFile7ReleaseEv");
  void vfn_193() asm("_ZN12AENormalFile11GetFileSizeEv");
  void vfn_194() asm("_ZTI9AEPakFile");
  void vfn_195() asm("_ZN9AEPakFileD2Ev");
  void vfn_196() asm("_ZN9AEPakFileD0Ev");
  void vfn_197() asm("_ZN9AEPakFile5WriteEjPv");
  void vfn_198() asm("_ZN9AEPakFile4ReadEjPv");
  void vfn_199() asm("_ZN9AEPakFile4SkipEj");
  void vfn_2() asm("_ZN7BeamGunD0Ev");
  void vfn_20() asm("_ZN9RocketGun9translateERKN11AbyssEngine6AEMath6VectorE");
  void vfn_200() asm("_ZN9AEPakFile7ReleaseEv");
  void vfn_201() asm("_ZN9AEPakFile11GetFileSizeEv");
  void vfn_202() asm("_ZTI6MTitle");
  void vfn_203() asm("_ZN6MTitleD2Ev");
  void vfn_204() asm("_ZN6MTitleD0Ev");
  void vfn_205() asm("_ZN6MTitle12OnInitializeEv");
  void vfn_206() asm("_ZN6MTitle9OnReleaseEv");
  void vfn_207() asm("_ZN6MTitle10OnKeyPressExx");
  void vfn_208() asm("_ZN6MTitle12OnKeyReleaseExx");
  void vfn_209() asm("_ZN6MTitle12OnTouchBeginEii");
  void vfn_21() asm("_ZN9ObjectGun10replaceGunEji");
  void vfn_210() asm("_ZN6MTitle11OnTouchMoveEii");
  void vfn_211() asm("_ZN6MTitle10OnTouchEndEii");
  void vfn_212() asm("_ZN11AbyssEngine18IApplicationModule12OnTouchBeginEiiPv");
  void vfn_213() asm("_ZN11AbyssEngine18IApplicationModule11OnTouchMoveEiiPv");
  void vfn_214() asm("_ZN11AbyssEngine18IApplicationModule10OnTouchEndEiiPv");
  void vfn_215() asm("_ZN6MTitle8OnUpdateEv");
  void vfn_216() asm("_ZN6MTitle10OnRender3DEv");
  void vfn_217() asm("_ZN6MTitle10OnRender2DEv");
  void vfn_218() asm("_ZN11AbyssEngine18IApplicationModule9OnSuspendEv");
  void vfn_219() asm("_ZN11AbyssEngine18IApplicationModule8OnResumeEv");
  void vfn_22() asm("_ZN9RocketGun11isRocketGunEv");
  void vfn_220() asm("_ZN6MTitle17ShowLoadingScreenEv");
  void vfn_221() asm("_ZTI11ModMainMenu");
  void vfn_222() asm("_ZN11ModMainMenuD2Ev");
  void vfn_223() asm("_ZN11ModMainMenuD0Ev");
  void vfn_224() asm("_ZN11ModMainMenu12OnInitializeEv");
  void vfn_225() asm("_ZN11ModMainMenu9OnReleaseEv");
  void vfn_226() asm("_ZN11ModMainMenu10OnKeyPressExx");
  void vfn_227() asm("_ZN11ModMainMenu12OnKeyReleaseExx");
  void vfn_228() asm("_ZN11ModMainMenu12OnTouchBeginEii");
  void vfn_229() asm("_ZN11ModMainMenu11OnTouchMoveEii");
  void vfn_23() asm("_ZN7BombGun9isBombGunEv");
  void vfn_230() asm("_ZN11ModMainMenu10OnTouchEndEii");
  void vfn_231() asm("_ZN11ModMainMenu12OnTouchBeginEiiPv");
  void vfn_232() asm("_ZN11ModMainMenu11OnTouchMoveEiiPv");
  void vfn_233() asm("_ZN11ModMainMenu10OnTouchEndEiiPv");
  void vfn_234() asm("_ZN11ModMainMenu8OnUpdateEv");
  void vfn_235() asm("_ZN11ModMainMenu10OnRender3DEv");
  void vfn_236() asm("_ZN11ModMainMenu10OnRender2DEv");
  void vfn_237() asm("_ZN11ModMainMenu9OnSuspendEv");
  void vfn_238() asm("_ZN11ModMainMenu8OnResumeEv");
  void vfn_239() asm("_ZN11ModMainMenu17ShowLoadingScreenEv");
  void vfn_24() asm("_ZTI15IParticleSystem");
  void vfn_240() asm("_ZTI14PlayerJumpgate");
  void vfn_241() asm("_ZN14PlayerJumpgateD2Ev");
  void vfn_242() asm("_ZN14PlayerJumpgateD0Ev");
  void vfn_243() asm("_ZN15PlayerStaticFar6renderEv");
  void vfn_244() asm("_ZN12PlayerStatic11getPositionEv");
  void vfn_245() asm("_ZN14PlayerJumpgate6updateEi");
  void vfn_246() asm("_ZN15PlayerStaticFar7collideEfff");
  void vfn_247() asm("_ZN15PlayerStaticFar12outerCollideEfff");
  void vfn_248() asm("_ZN14PlayerJumpgate11setPositionEfff");
  void vfn_249() asm("_ZN15PlayerStaticFar19getProjectionVectorERKN11AbyssEngine6AEMath6VectorE");
  void vfn_25() asm("_ZN15IParticleSystem4emitEi");
  void vfn_250() asm("_ZN15PlayerStaticFar25projectCollisionOnSurfaceERKN11AbyssEngine6AEMath6VectorE");
  void vfn_251() asm("_ZTI15PlayerStaticFar");
  void vfn_252() asm("_ZN15PlayerStaticFarD2Ev");
  void vfn_253() asm("_ZN15PlayerStaticFarD0Ev");
  void vfn_254() asm("_ZN15PlayerStaticFar6updateEi");
  void vfn_255() asm("_ZTI12PlayerStatic");
  void vfn_256() asm("_ZN12PlayerStaticD2Ev");
  void vfn_257() asm("_ZN12PlayerStaticD0Ev");
  void vfn_258() asm("_ZN12PlayerStatic6renderEv");
  void vfn_259() asm("_ZN12PlayerStatic6updateEi");
  void vfn_26() asm("_ZTI5MGame");
  void vfn_260() asm("_ZN12PlayerStatic7collideEfff");
  void vfn_261() asm("_ZN12PlayerStatic12outerCollideEfff");
  void vfn_262() asm("_ZTIN11AbyssEngine6StringE");
  void vfn_263() asm("_ZN11AbyssEngine6StringD2Ev");
  void vfn_264() asm("_ZN11AbyssEngine6StringD0Ev");
  void vfn_265() asm("_ZTI14PlayerWormHole");
  void vfn_266() asm("_ZN14PlayerWormHoleD2Ev");
  void vfn_267() asm("_ZN14PlayerWormHoleD0Ev");
  void vfn_268() asm("_ZN14PlayerWormHole6renderEv");
  void vfn_269() asm("_ZN14PlayerWormHole11getPositionEv");
  void vfn_27() asm("_ZN5MGameD2Ev");
  void vfn_270() asm("_ZN14PlayerWormHole6updateEi");
  void vfn_271() asm("_ZN14PlayerWormHole11setPositionEfff");
  void vfn_272() asm("_ZTIN11AbyssEngine18TextureLightShaderE");
  void vfn_273() asm("_ZN11AbyssEngine16ShaderBaseStructD2Ev");
  void vfn_274() asm("_ZN11AbyssEngine18TextureLightShaderD0Ev");
  void vfn_275() asm("_ZN11AbyssEngine18TextureLightShader4InitEPNS_6EngineE");
  void vfn_276() asm("_ZN11AbyssEngine18TextureLightShader14UpdateMeshDataEPNS_4MeshEPNS_6EngineE");
  void vfn_277() asm("_ZN11AbyssEngine18TextureLightShader11SetInActiveEv");
  void vfn_278() asm("_ZN11AbyssEngine16ShaderBaseStruct12RenderEffectEPNS_12FBOContainerEPNS_6EngineE");
  void vfn_279() asm("_ZN11AbyssEngine16ShaderBaseStruct12RenderEffectEPNS_12FBOContainerEPNS_6EngineEfNS_6AEMath6VectorE");
  void vfn_28() asm("_ZN5MGameD0Ev");
  void vfn_280() asm("_ZN11AbyssEngine16ShaderBaseStruct12RenderEffectEPNS_12FBOContainerERS2_PNS_6EngineE");
  void vfn_281() asm("_ZN11AbyssEngine16ShaderBaseStruct12RenderEffectEPNS_12FBOContainerERS2_PNS_6EngineEfNS_6AEMath6VectorE");
  void vfn_282() asm("_ZN11AbyssEngine16ShaderBaseStruct12DeleteShaderEv");
  void vfn_283() asm("_ZN11AbyssEngine16ShaderBaseStruct9UseShaderEb");
  void vfn_29() asm("_ZN5MGame12OnInitializeEv");
  void vfn_3() asm("_ZN7BeamGun10setEnemiesEP5ArrayIP6PlayerE");
  void vfn_30() asm("_ZN5MGame9OnReleaseEv");
  void vfn_31() asm("_ZN5MGame10OnKeyPressExx");
  void vfn_32() asm("_ZN5MGame12OnKeyReleaseExx");
  void vfn_33() asm("_ZN5MGame12OnTouchBeginEii");
  void vfn_34() asm("_ZN5MGame11OnTouchMoveEii");
  void vfn_35() asm("_ZN5MGame10OnTouchEndEii");
  void vfn_36() asm("_ZN5MGame12OnTouchBeginEiiPv");
  void vfn_37() asm("_ZN5MGame11OnTouchMoveEiiPv");
  void vfn_38() asm("_ZN5MGame10OnTouchEndEiiPv");
  void vfn_39() asm("_ZN5MGame8OnUpdateEv");
  void vfn_4() asm("_ZN7BeamGun8setEnemyEP6Player");
  void vfn_40() asm("_ZN5MGame10OnRender3DEv");
  void vfn_41() asm("_ZN5MGame10OnRender2DEv");
  void vfn_42() asm("_ZN5MGame9OnSuspendEv");
  void vfn_43() asm("_ZN5MGame8OnResumeEv");
  void vfn_44() asm("_ZN5MGame17ShowLoadingScreenEv");
  void vfn_45() asm("_ZTI7MineGun");
  void vfn_46() asm("_ZN7MineGunD2Ev");
  void vfn_47() asm("_ZN7MineGunD0Ev");
  void vfn_48() asm("_ZN7MineGun6updateEi");
  void vfn_49() asm("_ZN7MineGun6renderEv");
  void vfn_5() asm("_ZN7BeamGun6updateEi");
  void vfn_50() asm("_ZN9ObjectGun9translateERKN11AbyssEngine6AEMath6VectorE");
  void vfn_51() asm("_ZN7MineGun9isMineGunEv");
  void vfn_52() asm("_ZTI7Mission");
  void vfn_53() asm("_ZN7MissionD2Ev");
  void vfn_54() asm("_ZN7MissionD0Ev");
  void vfn_55() asm("_ZTI10ModStation");
  void vfn_56() asm("_ZN10ModStationD2Ev");
  void vfn_57() asm("_ZN10ModStationD0Ev");
  void vfn_58() asm("_ZN10ModStation12OnInitializeEv");
  void vfn_59() asm("_ZN10ModStation9OnReleaseEv");
  void vfn_6() asm("_ZN7BeamGun6renderEv");
  void vfn_60() asm("_ZN10ModStation10OnKeyPressExx");
  void vfn_61() asm("_ZN10ModStation12OnKeyReleaseExx");
  void vfn_62() asm("_ZN10ModStation12OnTouchBeginEii");
  void vfn_63() asm("_ZN10ModStation11OnTouchMoveEii");
  void vfn_64() asm("_ZN10ModStation10OnTouchEndEii");
  void vfn_65() asm("_ZN10ModStation12OnTouchBeginEiiPv");
  void vfn_66() asm("_ZN10ModStation11OnTouchMoveEiiPv");
  void vfn_67() asm("_ZN10ModStation10OnTouchEndEiiPv");
  void vfn_68() asm("_ZN10ModStation8OnUpdateEv");
  void vfn_69() asm("_ZN10ModStation10OnRender3DEv");
  void vfn_7() asm("_ZN7BeamGun9translateERKN11AbyssEngine6AEMath6VectorE");
  void vfn_70() asm("_ZN10ModStation10OnRender2DEv");
  void vfn_71() asm("_ZN10ModStation9OnSuspendEv");
  void vfn_72() asm("_ZN10ModStation8OnResumeEv");
  void vfn_73() asm("_ZN10ModStation17ShowLoadingScreenEv");
  void vfn_74() asm("_ZTI9ObjectGun");
  void vfn_75() asm("_ZN9ObjectGunD2Ev");
  void vfn_76() asm("_ZN9ObjectGunD0Ev");
  void vfn_77() asm("_ZN9ObjectGun6updateEi");
  void vfn_78() asm("_ZN9ObjectGun6renderEv");
  void vfn_79() asm("_ZTI14PlayerAsteroid");
  void vfn_8() asm("_ZN7BeamGun10replaceGunEji");
  void vfn_80() asm("_ZN14PlayerAsteroidD2Ev");
  void vfn_81() asm("_ZN14PlayerAsteroidD0Ev");
  void vfn_82() asm("_ZN8KIPlayer12setShipGroupEP10AEGeometryib");
  void vfn_83() asm("_ZN8KIPlayer5awakeEv");
  void vfn_84() asm("_ZN8KIPlayer17setWingmanCommandEiPS_");
  void vfn_85() asm("_ZN8KIPlayer8setLevelEP5Level");
  void vfn_86() asm("_ZN8KIPlayer6reviveEv");
  void vfn_87() asm("_ZN8KIPlayer8setSpeedEf");
  void vfn_88() asm("_ZN14PlayerAsteroid9translateERKN11AbyssEngine6AEMath6VectorE");
  void vfn_89() asm("_ZN14PlayerAsteroid6renderEv");
  void vfn_9() asm("_ZN11AbstractGun11isRocketGunEv");
  void vfn_90() asm("_ZN14PlayerAsteroid11getPositionEv");
  void vfn_91() asm("_ZN14PlayerAsteroid8initPushERKN11AbyssEngine6AEMath6VectorEi");
  void vfn_92() asm("_ZN14PlayerAsteroid4pushEi");
  void vfn_93() asm("_ZN14PlayerAsteroid6updateEi");
  void vfn_94() asm("_ZN14PlayerAsteroid7collideEfff");
  void vfn_95() asm("_ZN14PlayerAsteroid12outerCollideEfff");
  void vfn_96() asm("_ZN8KIPlayer12outerCollideERKN11AbyssEngine6AEMath6VectorE");
  void vfn_97() asm("_ZN14PlayerAsteroid11setPositionERKN11AbyssEngine6AEMath6VectorE");
  void vfn_98() asm("_ZN8KIPlayer11setPositionEfff");
  void vfn_99() asm("_ZN8KIPlayer8getSpeedEv");
}

// _ZTV7BeamGun (target 0x20e4ac, 14 slots)
static void* const _vt_20e4ac[] = {
  (void*)0,
  (void*)&vfn_0,
  (void*)&vfn_1,
  (void*)&vfn_2,
  (void*)&vfn_3,
  (void*)&vfn_4,
  (void*)&vfn_5,
  (void*)&vfn_6,
  (void*)&vfn_7,
  (void*)&vfn_8,
  (void*)&vfn_9,
  (void*)&vfn_10,
  (void*)&vfn_11,
  (void*)&vfn_12,
};
// _ZTV7BombGun (target 0x20de24, 14 slots)
static void* const _vt_20de24[] = {
  (void*)0,
  (void*)&vfn_13,
  (void*)&vfn_14,
  (void*)&vfn_15,
  (void*)&vfn_16,
  (void*)&vfn_17,
  (void*)&vfn_18,
  (void*)&vfn_19,
  (void*)&vfn_20,
  (void*)&vfn_21,
  (void*)&vfn_22,
  (void*)&vfn_23,
  (void*)&vfn_11,
  (void*)&vfn_12,
};
// _ZTV15IParticleSystem (target 0x20e54c, 9 slots)
static void* const _vt_20e54c[] = {
  (void*)0,
  (void*)&vfn_24,
  (void*)0,
  (void*)&vfn_25,
  (void*)0,
  (void*)0,
  (void*)0,
  (void*)0,
  (void*)0,
};
// _ZTV5MGame (target 0x20e4f0, 20 slots)
static void* const _vt_20e4f0[] = {
  (void*)0,
  (void*)&vfn_26,
  (void*)&vfn_27,
  (void*)&vfn_28,
  (void*)&vfn_29,
  (void*)&vfn_30,
  (void*)&vfn_31,
  (void*)&vfn_32,
  (void*)&vfn_33,
  (void*)&vfn_34,
  (void*)&vfn_35,
  (void*)&vfn_36,
  (void*)&vfn_37,
  (void*)&vfn_38,
  (void*)&vfn_39,
  (void*)&vfn_40,
  (void*)&vfn_41,
  (void*)&vfn_42,
  (void*)&vfn_43,
  (void*)&vfn_44,
};
// _ZTV7MineGun (target 0x20e000, 14 slots)
static void* const _vt_20e000[] = {
  (void*)0,
  (void*)&vfn_45,
  (void*)&vfn_46,
  (void*)&vfn_47,
  (void*)&vfn_16,
  (void*)&vfn_17,
  (void*)&vfn_48,
  (void*)&vfn_49,
  (void*)&vfn_50,
  (void*)&vfn_21,
  (void*)&vfn_9,
  (void*)&vfn_10,
  (void*)&vfn_51,
  (void*)&vfn_12,
};
// _ZTV7Mission (target 0x20e12c, 4 slots)
static void* const _vt_20e12c[] = {
  (void*)0,
  (void*)&vfn_52,
  (void*)&vfn_53,
  (void*)&vfn_54,
};
// _ZTV10ModStation (target 0x20d9e4, 20 slots)
static void* const _vt_20d9e4[] = {
  (void*)0,
  (void*)&vfn_55,
  (void*)&vfn_56,
  (void*)&vfn_57,
  (void*)&vfn_58,
  (void*)&vfn_59,
  (void*)&vfn_60,
  (void*)&vfn_61,
  (void*)&vfn_62,
  (void*)&vfn_63,
  (void*)&vfn_64,
  (void*)&vfn_65,
  (void*)&vfn_66,
  (void*)&vfn_67,
  (void*)&vfn_68,
  (void*)&vfn_69,
  (void*)&vfn_70,
  (void*)&vfn_71,
  (void*)&vfn_72,
  (void*)&vfn_73,
};
// _ZTV9ObjectGun (target 0x20e250, 14 slots)
static void* const _vt_20e250[] = {
  (void*)0,
  (void*)&vfn_74,
  (void*)&vfn_75,
  (void*)&vfn_76,
  (void*)&vfn_16,
  (void*)&vfn_17,
  (void*)&vfn_77,
  (void*)&vfn_78,
  (void*)&vfn_50,
  (void*)&vfn_21,
  (void*)&vfn_9,
  (void*)&vfn_10,
  (void*)&vfn_11,
  (void*)&vfn_12,
};
// _ZTV14PlayerAsteroid (target 0x20dc24, 26 slots)
static void* const _vt_20dc24[] = {
  (void*)0,
  (void*)&vfn_79,
  (void*)&vfn_80,
  (void*)&vfn_81,
  (void*)&vfn_82,
  (void*)&vfn_83,
  (void*)&vfn_84,
  (void*)&vfn_85,
  (void*)&vfn_86,
  (void*)&vfn_87,
  (void*)&vfn_88,
  (void*)&vfn_89,
  (void*)&vfn_90,
  (void*)&vfn_91,
  (void*)&vfn_92,
  (void*)&vfn_93,
  (void*)&vfn_94,
  (void*)&vfn_95,
  (void*)&vfn_96,
  (void*)&vfn_97,
  (void*)&vfn_98,
  (void*)&vfn_99,
  (void*)&vfn_100,
  (void*)&vfn_101,
  (void*)&vfn_102,
  (void*)&vfn_103,
};
// _ZTV13PlayerStation (target 0x20ddb0, 26 slots)
static void* const _vt_20ddb0[] = {
  (void*)0,
  (void*)&vfn_104,
  (void*)&vfn_105,
  (void*)&vfn_106,
  (void*)&vfn_82,
  (void*)&vfn_83,
  (void*)&vfn_84,
  (void*)&vfn_85,
  (void*)&vfn_86,
  (void*)&vfn_87,
  (void*)&vfn_107,
  (void*)&vfn_108,
  (void*)&vfn_109,
  (void*)&vfn_110,
  (void*)&vfn_111,
  (void*)&vfn_112,
  (void*)&vfn_113,
  (void*)&vfn_114,
  (void*)&vfn_115,
  (void*)&vfn_116,
  (void*)&vfn_98,
  (void*)&vfn_99,
  (void*)&vfn_117,
  (void*)&vfn_101,
  (void*)&vfn_118,
  (void*)&vfn_103,
};
// _ZTV9RocketGun (target 0x20e20c, 14 slots)
static void* const _vt_20e20c[] = {
  (void*)0,
  (void*)&vfn_119,
  (void*)&vfn_120,
  (void*)&vfn_121,
  (void*)&vfn_16,
  (void*)&vfn_17,
  (void*)&vfn_122,
  (void*)&vfn_123,
  (void*)&vfn_20,
  (void*)&vfn_21,
  (void*)&vfn_22,
  (void*)&vfn_10,
  (void*)&vfn_11,
  (void*)&vfn_12,
};
// _ZTV8Waypoint (target 0x20e0b8, 26 slots)
static void* const _vt_20e0b8[] = {
  (void*)0,
  (void*)&vfn_124,
  (void*)&vfn_125,
  (void*)&vfn_126,
  (void*)&vfn_82,
  (void*)&vfn_83,
  (void*)&vfn_84,
  (void*)&vfn_85,
  (void*)&vfn_86,
  (void*)&vfn_87,
  (void*)&vfn_127,
  (void*)&vfn_128,
  (void*)&vfn_129,
  (void*)&vfn_110,
  (void*)&vfn_111,
  (void*)&vfn_130,
  (void*)&vfn_131,
  (void*)&vfn_132,
  (void*)&vfn_96,
  (void*)&vfn_133,
  (void*)&vfn_98,
  (void*)&vfn_99,
  (void*)&vfn_134,
  (void*)&vfn_101,
  (void*)&vfn_102,
  (void*)&vfn_103,
};
// _ZTV20FileInterfaceAndroid (target 0x20cbb0, 24 slots)
static void* const _vt_20cbb0[] = {
  (void*)0,
  (void*)&vfn_135,
  (void*)&vfn_136,
  (void*)&vfn_137,
  (void*)&vfn_138,
  (void*)&vfn_139,
  (void*)&vfn_140,
  (void*)&vfn_141,
  (void*)&vfn_142,
  (void*)&vfn_143,
  (void*)&vfn_144,
  (void*)&vfn_145,
  (void*)&vfn_146,
  (void*)&vfn_147,
  (void*)&vfn_148,
  (void*)&vfn_149,
  (void*)&vfn_150,
  (void*)&vfn_151,
  (void*)&vfn_152,
  (void*)&vfn_153,
  (void*)&vfn_154,
  (void*)&vfn_155,
  (void*)&vfn_156,
  (void*)&vfn_157,
};
// _ZTV13PlayerFighter (target 0x20db3c, 26 slots)
static void* const _vt_20db3c[] = {
  (void*)0,
  (void*)&vfn_158,
  (void*)&vfn_159,
  (void*)&vfn_160,
  (void*)&vfn_161,
  (void*)&vfn_162,
  (void*)&vfn_163,
  (void*)&vfn_164,
  (void*)&vfn_165,
  (void*)&vfn_166,
  (void*)&vfn_127,
  (void*)&vfn_167,
  (void*)&vfn_168,
  (void*)&vfn_169,
  (void*)&vfn_170,
  (void*)&vfn_171,
  (void*)&vfn_172,
  (void*)&vfn_173,
  (void*)&vfn_96,
  (void*)&vfn_174,
  (void*)&vfn_175,
  (void*)&vfn_99,
  (void*)&vfn_134,
  (void*)&vfn_101,
  (void*)&vfn_102,
  (void*)&vfn_103,
};
// _ZTV12PlayerTurret (target 0x20e044, 26 slots)
static void* const _vt_20e044[] = {
  (void*)0,
  (void*)&vfn_176,
  (void*)&vfn_177,
  (void*)&vfn_178,
  (void*)&vfn_82,
  (void*)&vfn_83,
  (void*)&vfn_84,
  (void*)&vfn_179,
  (void*)&vfn_180,
  (void*)&vfn_87,
  (void*)&vfn_127,
  (void*)&vfn_181,
  (void*)&vfn_168,
  (void*)&vfn_110,
  (void*)&vfn_111,
  (void*)&vfn_182,
  (void*)&vfn_183,
  (void*)&vfn_184,
  (void*)&vfn_96,
  (void*)&vfn_185,
  (void*)&vfn_98,
  (void*)&vfn_99,
  (void*)&vfn_134,
  (void*)&vfn_101,
  (void*)&vfn_102,
  (void*)&vfn_103,
};
// _ZTV12AENormalFile (target 0x20cc48, 9 slots)
static void* const _vt_20cc48[] = {
  (void*)0,
  (void*)&vfn_186,
  (void*)&vfn_187,
  (void*)&vfn_188,
  (void*)&vfn_189,
  (void*)&vfn_190,
  (void*)&vfn_191,
  (void*)&vfn_192,
  (void*)&vfn_193,
};
// _ZTV9AEPakFile (target 0x20cc24, 9 slots)
static void* const _vt_20cc24[] = {
  (void*)0,
  (void*)&vfn_194,
  (void*)&vfn_195,
  (void*)&vfn_196,
  (void*)&vfn_197,
  (void*)&vfn_198,
  (void*)&vfn_199,
  (void*)&vfn_200,
  (void*)&vfn_201,
};
// _ZTV6MTitle (target 0x20d7d0, 20 slots)
static void* const _vt_20d7d0[] = {
  (void*)0,
  (void*)&vfn_202,
  (void*)&vfn_203,
  (void*)&vfn_204,
  (void*)&vfn_205,
  (void*)&vfn_206,
  (void*)&vfn_207,
  (void*)&vfn_208,
  (void*)&vfn_209,
  (void*)&vfn_210,
  (void*)&vfn_211,
  (void*)&vfn_212,
  (void*)&vfn_213,
  (void*)&vfn_214,
  (void*)&vfn_215,
  (void*)&vfn_216,
  (void*)&vfn_217,
  (void*)&vfn_218,
  (void*)&vfn_219,
  (void*)&vfn_220,
};
// _ZTV11ModMainMenu (target 0x20e3dc, 20 slots)
static void* const _vt_20e3dc[] = {
  (void*)0,
  (void*)&vfn_221,
  (void*)&vfn_222,
  (void*)&vfn_223,
  (void*)&vfn_224,
  (void*)&vfn_225,
  (void*)&vfn_226,
  (void*)&vfn_227,
  (void*)&vfn_228,
  (void*)&vfn_229,
  (void*)&vfn_230,
  (void*)&vfn_231,
  (void*)&vfn_232,
  (void*)&vfn_233,
  (void*)&vfn_234,
  (void*)&vfn_235,
  (void*)&vfn_236,
  (void*)&vfn_237,
  (void*)&vfn_238,
  (void*)&vfn_239,
};
// _ZTV14PlayerJumpgate (target 0x20d85c, 26 slots)
static void* const _vt_20d85c[] = {
  (void*)0,
  (void*)&vfn_240,
  (void*)&vfn_241,
  (void*)&vfn_242,
  (void*)&vfn_82,
  (void*)&vfn_83,
  (void*)&vfn_84,
  (void*)&vfn_85,
  (void*)&vfn_86,
  (void*)&vfn_87,
  (void*)&vfn_107,
  (void*)&vfn_243,
  (void*)&vfn_244,
  (void*)&vfn_110,
  (void*)&vfn_111,
  (void*)&vfn_245,
  (void*)&vfn_246,
  (void*)&vfn_247,
  (void*)&vfn_96,
  (void*)&vfn_133,
  (void*)&vfn_248,
  (void*)&vfn_99,
  (void*)&vfn_249,
  (void*)&vfn_101,
  (void*)&vfn_250,
  (void*)&vfn_103,
};
// _ZTV15PlayerStaticFar (target 0x20dca4, 26 slots)
static void* const _vt_20dca4[] = {
  (void*)0,
  (void*)&vfn_251,
  (void*)&vfn_252,
  (void*)&vfn_253,
  (void*)&vfn_82,
  (void*)&vfn_83,
  (void*)&vfn_84,
  (void*)&vfn_85,
  (void*)&vfn_86,
  (void*)&vfn_87,
  (void*)&vfn_107,
  (void*)&vfn_243,
  (void*)&vfn_244,
  (void*)&vfn_110,
  (void*)&vfn_111,
  (void*)&vfn_254,
  (void*)&vfn_246,
  (void*)&vfn_247,
  (void*)&vfn_96,
  (void*)&vfn_133,
  (void*)&vfn_98,
  (void*)&vfn_99,
  (void*)&vfn_249,
  (void*)&vfn_101,
  (void*)&vfn_250,
  (void*)&vfn_103,
};
// _ZTV12PlayerStatic (target 0x20dbb0, 26 slots)
static void* const _vt_20dbb0[] = {
  (void*)0,
  (void*)&vfn_255,
  (void*)&vfn_256,
  (void*)&vfn_257,
  (void*)&vfn_82,
  (void*)&vfn_83,
  (void*)&vfn_84,
  (void*)&vfn_85,
  (void*)&vfn_86,
  (void*)&vfn_87,
  (void*)&vfn_107,
  (void*)&vfn_258,
  (void*)&vfn_244,
  (void*)&vfn_110,
  (void*)&vfn_111,
  (void*)&vfn_259,
  (void*)&vfn_260,
  (void*)&vfn_261,
  (void*)&vfn_96,
  (void*)&vfn_133,
  (void*)&vfn_98,
  (void*)&vfn_99,
  (void*)&vfn_134,
  (void*)&vfn_101,
  (void*)&vfn_102,
  (void*)&vfn_103,
};
// _ZTVN11AbyssEngine6StringE (target 0x20cc8c, 4 slots)
static void* const _vt_20cc8c[] = {
  (void*)0,
  (void*)&vfn_262,
  (void*)&vfn_263,
  (void*)&vfn_264,
};
// _ZTV14PlayerWormHole (target 0x20d8d0, 26 slots)
static void* const _vt_20d8d0[] = {
  (void*)0,
  (void*)&vfn_265,
  (void*)&vfn_266,
  (void*)&vfn_267,
  (void*)&vfn_82,
  (void*)&vfn_83,
  (void*)&vfn_84,
  (void*)&vfn_85,
  (void*)&vfn_86,
  (void*)&vfn_87,
  (void*)&vfn_107,
  (void*)&vfn_268,
  (void*)&vfn_269,
  (void*)&vfn_110,
  (void*)&vfn_111,
  (void*)&vfn_270,
  (void*)&vfn_246,
  (void*)&vfn_247,
  (void*)&vfn_96,
  (void*)&vfn_133,
  (void*)&vfn_271,
  (void*)&vfn_99,
  (void*)&vfn_249,
  (void*)&vfn_101,
  (void*)&vfn_250,
  (void*)&vfn_103,
};
// _ZTVN11AbyssEngine18TextureLightShaderE (target 0x20d1fc, 13 slots)
static void* const _vt_20d1fc[] = {
  (void*)0,
  (void*)&vfn_272,
  (void*)&vfn_273,
  (void*)&vfn_274,
  (void*)&vfn_275,
  (void*)&vfn_276,
  (void*)&vfn_277,
  (void*)&vfn_278,
  (void*)&vfn_279,
  (void*)&vfn_280,
  (void*)&vfn_281,
  (void*)&vfn_282,
  (void*)&vfn_283,
};

extern "C" void* BeamGun_vtable; void* BeamGun_vtable = (void*)_vt_20e4ac;
extern "C" void* BombGun_vtable; void* BombGun_vtable = (void*)_vt_20de24;
extern "C" void* IParticleSystem_vtable; void* IParticleSystem_vtable = (void*)_vt_20e54c;
extern "C" void* MGame_vtable; void* MGame_vtable = (void*)_vt_20e4f0;
extern "C" void* MineGun_vtable; void* MineGun_vtable = (void*)_vt_20e000;
extern "C" void* Mission_vtable; void* Mission_vtable = (void*)_vt_20e12c;
extern "C" void* ModStation_vtable; void* ModStation_vtable = (void*)_vt_20d9e4;
extern "C" void* ObjectGun_vtable; void* ObjectGun_vtable = (void*)_vt_20e250;
extern "C" void* PlayerAsteroid_vtable; void* PlayerAsteroid_vtable = (void*)_vt_20dc24;
extern "C" void* PlayerStation_vtable; void* PlayerStation_vtable = (void*)_vt_20ddb0;
extern "C" void* RocketGun_vtable; void* RocketGun_vtable = (void*)_vt_20e20c;
extern "C" void* Waypoint_vtable; void* Waypoint_vtable = (void*)_vt_20e0b8;
extern "C" void* gFIAVtable; void* gFIAVtable = (void*)_vt_20cbb0;
extern "C" void* gFIAVtable_dtor; void* gFIAVtable_dtor = (void*)_vt_20cbb0;
extern "C" void* gFIAVtable_file; void* gFIAVtable_file = (void*)_vt_20cbb0;
extern "C" void* gFIAVtable_obj; void* gFIAVtable_obj = (void*)_vt_20cbb0;
extern "C" void* gFIAVtable_or; void* gFIAVtable_or = (void*)_vt_20cbb0;
extern "C" void* gFIAVtable_ow; void* gFIAVtable_ow = (void*)_vt_20cbb0;
extern "C" void* gFIAVtable_zip; void* gFIAVtable_zip = (void*)_vt_20cbb0;
extern "C" void* gPFC_vtable; void* gPFC_vtable = (void*)_vt_20db3c;
extern "C" void* gPlayerTurretVtable; void* gPlayerTurretVtable = (void*)_vt_20e044;
extern "C" void* gPlayerTurretVtable_ctor; void* gPlayerTurretVtable_ctor = (void*)_vt_20e044;
extern "C" void* g_AENormalFile_vtable; void* g_AENormalFile_vtable = (void*)_vt_20cc48;
extern "C" void* g_AEPakFile_vtable; void* g_AEPakFile_vtable = (void*)_vt_20cc24;
extern "C" void* g_MTitle_vtable; void* g_MTitle_vtable = (void*)_vt_20d7d0;
extern "C" void* g_ModMainMenu_vtable; void* g_ModMainMenu_vtable = (void*)_vt_20e3dc;
extern "C" void* g_PlayerJumpgate_vtable; void* g_PlayerJumpgate_vtable = (void*)_vt_20d85c;
extern "C" void* g_PlayerStaticFar_vtable; void* g_PlayerStaticFar_vtable = (void*)_vt_20dca4;
extern "C" void* g_PlayerStatic_vtable; void* g_PlayerStatic_vtable = (void*)_vt_20dbb0;
extern "C" void* g_String_vtable; void* g_String_vtable = (void*)_vt_20cc8c;
extern "C" void* g_mgameVtable; void* g_mgameVtable = (void*)_vt_20e4f0;
extern "C" void* g_msc_vtable; void* g_msc_vtable = (void*)_vt_20d9e4;
extern "C" void* g_playerWormHole_vtable; void* g_playerWormHole_vtable = (void*)_vt_20d8d0;
extern "C" void* g_tls_vtableBase; void* g_tls_vtableBase = (void*)_vt_20d1fc;
