#!/usr/bin/env python3
# Reconstruct real C++ vtables for the *_vtable weak-stub symbols, so virtual dispatch works at
# runtime. Each target vtable lives in .data.rel.ro and is filled by R_ARM_ABS32 relocations that
# name the virtual functions (all recovered in our corpus). We:
#   1) resolve each stub -> its target _ZTV address by disassembling the referencing ctor and finding
#      the vtable-range literal it stores (robust; no name guessing),
#   2) read the per-slot relocations -> ordered function symbols,
#   3) emit an array of asm-aliased pointers to those functions; the stub var holds the array base
#      (our code does `(char*)stub + 8` to get the Itanium vptr).
# Run from repo root (host); shells to the guest for objdump. Writes work/runtime/vtables.cpp.
import subprocess, re, os, glob
REPO=os.path.dirname(os.path.dirname(os.path.abspath(__file__))); os.chdir(REPO)
SO="../_work/bins/android_2.0.16_libgof2hdaa.so"
def orb(cmd): return subprocess.run(["orb","run","bash","-lc",cmd],capture_output=True,text=True).stdout

# persistent target symbol/reloc dumps (build/full is wiped by `make reassemble`)
T="work/runtime/target"; os.makedirs(T,exist_ok=True)
if not os.path.exists(T+"/dynsyms.txt"):
    orb("arm-linux-gnueabihf-readelf --dyn-syms -W %s > %s/dynsyms.txt"%(SO,T))
    orb("arm-linux-gnueabihf-readelf -r -W %s > %s/relocs.txt"%(SO,T))

# 1) _ZTV symbols: base addr -> (size, mangled); + class-basename -> base addr
ztv={}; cls2base={}
for ln in open(T+"/dynsyms.txt"):
    if "_ZTV" not in ln: continue
    p=ln.split()
    try: addr=int(p[1],16); size=int(p[2])
    except (ValueError,IndexError): continue
    name=next((t for t in p if t.startswith("_ZTV")),None)
    if not name: continue
    ztv[addr]=(size,name)
    dem=subprocess.run(["orb","run","arm-linux-gnueabihf-c++filt",name],capture_output=True,text=True).stdout.strip()
    cl=dem.replace("vtable for ","").strip()           # e.g. "AbyssEngine::String" or "PlayerFighter"
    cls2base[cl]=addr; cls2base[cl.split("::")[-1]]=addr  # full + basename
ztv_lo=min(ztv); ztv_hi=max(a+s for a,(s,_) in ztv.items())

# 2) relocations: offset -> (type, val, sym)
relocs={}
for ln in open(T+"/relocs.txt"):
    m=re.match(r'^([0-9a-f]{8})\s+[0-9a-f]+\s+(\S+)\s+([0-9a-f]+)\s*(\S+)?',ln)
    if m: relocs[int(m.group(1),16)]=(m.group(2),m.group(3),m.group(4))

# 3) dynsym vaddr(thumb-stripped) -> mangled FUNC name (for RELATIVE addends)
va2name={}
for ln in open(T+"/dynsyms.txt"):
    p=ln.split()
    if len(p)>=8 and re.fullmatch(r'[0-9a-f]{8}',p[1]) and p[3]=="FUNC":
        va2name[int(p[1],16)&~1]=p[7]

# stub list from the corpus's hidden-extern declarations (stateless: independent of whether a prior
# vtables.cpp already defined some — undef.txt would wrongly omit those).
_decls=subprocess.run(["grep","-rhE",r'visibility..hidden',"work/classes"],capture_output=True,text=True).stdout
stubs=sorted(set(re.findall(r'\b([A-Za-z_][A-Za-z0-9_]*[Vv]table[A-Za-z0-9_]*)\b',_decls)))
aliases={}   # mangled -> C alias ident
def alias(mangled):
    if mangled not in aliases: aliases[mangled]="vfn_%d"%len(aliases)
    return aliases[mangled]

by_base={}   # base -> (size, mangled, [entries])   ; stub2base -> base
stub2base={}; report=[]
for s in stubs:
    files=subprocess.run(["grep","-rl",s,"work/classes"],capture_output=True,text=True).stdout.split("\n")
    files=[f for f in files if f.endswith(".cpp") and "/src/" in f]
    if not files: report.append((s,"NO REF","")); continue
    classes=[f.split("/")[2] for f in files]
    cls=max(set(classes),key=classes.count)   # dominant class dir = the ctor that stores this vptr
    base=cls2base.get(cls) or cls2base.get(cls.split("::")[-1])
    if base is None: report.append((s,"NO _ZTV for class %s"%cls,"")); continue
    stub2base[s]=base
    if base not in by_base:
        size,mangled=ztv[base]; entries=[]
        for i in range(size//4):
            off=base+4*i; e=None
            if off in relocs:
                typ,val,sym=relocs[off]
                if typ=="R_ARM_ABS32" and sym and sym.startswith("_Z"): e=sym
                elif typ=="R_ARM_RELATIVE":
                    nm=va2name.get(int(val,16)&~1)
                    if nm and nm.startswith("_Z") and not nm.startswith("_ZT"): e=nm
            entries.append(e)
            if e: alias(e)
        by_base[base]=(size,mangled,entries)
    size,mangled,_=by_base[base]
    report.append((s,"0x%x"%base,"%s  %dB"%(mangled,size)))

# 4) emit (one array per unique vtable; all stub names that resolve to it alias the same array)
os.makedirs("work/runtime",exist_ok=True)
with open("work/runtime/vtables.cpp","w") as o:
    o.write("// AUTO-GENERATED by work/gen_vtables.py — real vtables for the *vtable* stub symbols.\n")
    o.write("// Each array reproduces the target's .data.rel.ro vtable (Itanium layout); each stub var\n")
    o.write("// holds the array base so the engine's `(char*)stub + 8` yields the correct vptr.\n\n")
    o.write('extern "C" {\n')
    for mangled,al in sorted(aliases.items(),key=lambda kv:kv[1]):
        o.write('  void %s() asm("%s");\n'%(al,mangled))
    o.write("}\n\n")
    base2arr={}
    for base,(size,mangled,entries) in by_base.items():
        arr="_vt_%x"%base; base2arr[base]=arr
        o.write("// %s (target 0x%x, %d slots)\n"%(mangled,base,size//4))
        o.write("static void* const %s[] = {\n"%arr)
        for e in entries: o.write("  (void*)%s,\n"%(("&"+aliases[e]) if e else "0"))
        o.write("};\n")
    o.write("\n")
    for s,base in stub2base.items():
        o.write('extern "C" void* %s; void* %s = (void*)%s;\n'%(s,s,base2arr[base]))

print("=== stub -> target vtable resolution ===")
for s,a,b in report: print("  %-28s %-12s %s"%(s,a,b))
print("\nemitted work/runtime/vtables.cpp : %d stubs -> %d unique vtables, %d vfns"%(len(stub2base),len(by_base),len(aliases)))
