#!/usr/bin/env python3
# Recover real values for const data-table stubs (.rodata / .data). For each table-named stub:
#   1) parse its corpus extern decl -> C type, element count, array-vs-pointer form,
#   2) read the referencing fn's .md target disasm for the PIC pattern `ldr rX,[pool]; add rX,pc`
#      -> table address = (add_insn+4) + *pool,  (handles thumb pc),
#   3) classify by section; if in .rodata/.data, extract element bytes from the .so,
#   4) emit a real C++ definition (work/runtime/consts.cpp) overriding the weak stub.
# Single-data-ref functions resolve cleanly; multi-ref ones are reported for reactive recovery.
import subprocess, re, os, glob
REPO=os.path.dirname(os.path.dirname(os.path.abspath(__file__))); os.chdir(REPO)
SO="../_work/bins/android_2.0.16_libgof2hdaa.so"
RODATA=(0x1c9e10,0x20b977); DATA=(0x214000,0x21696c)
SZ={"char":1,"int8_t":1,"uint8_t":1,"unsigned char":1,"short":2,"int16_t":2,"uint16_t":2,
    "int":4,"int32_t":4,"uint32_t":4,"unsigned":4,"unsigned int":4,"float":4,"void*":4,"void *":4}
def orb(c): return subprocess.run(["orb","run","bash","-lc",c],capture_output=True,text=True).stdout
def rd(elf_addr,n):
    a0=elf_addr&~0xf
    out=orb("arm-linux-gnueabihf-objdump -s --start-address=0x%x --stop-address=0x%x %s 2>/dev/null"%(a0,elf_addr+n+16,SO))
    m={}
    for ln in out.splitlines():
        g=re.match(r'\s*([0-9a-f]+)\s+([0-9a-f ]+?)\s{2,}',ln)
        if not g: continue
        base=int(g.group(1),16); h=g.group(2).replace(" ","")
        for i in range(0,len(h),2): m[base+i//2]=int(h[i:i+2],16)
    return bytes(m.get(elf_addr+i,0) for i in range(n))

if os.path.exists("work/runtime/consts.list"):
    CANDIDATES=[l.strip() for l in open("work/runtime/consts.list") if l.strip()]
else:
    # full stub names from undef.txt that look like const tables (exclude vtables, already handled)
    out=subprocess.run(["grep","-iE",r'table|definition|bank|_data|geometry|preset|verts|indices|coords|palette|lookup',"build/full/undef.txt"],capture_output=True,text=True).stdout
    CANDIDATES=[l.strip() for l in out.splitlines() if l.strip() and "vtable" not in l.lower()]

def decl_of(stub):
    out=subprocess.run(["grep","-rhE",r'\bextern\b.*\b'+re.escape(stub)+r'\b',"work/classes"],capture_output=True,text=True).stdout
    for ln in out.splitlines():
        m=re.search(r'(const\s+)?([A-Za-z_]\w*)\s*(\*?)\s*'+re.escape(stub)+r'\s*(\[\s*(\d*)\s*\])?',ln)
        if m:
            ctype=m.group(2); ptr=bool(m.group(3)); cnt=m.group(5)
            return ctype,(int(cnt) if cnt else None),ptr
    return None
def ref_addr(stub):
    f=subprocess.run(["grep","-rl",stub,"work/classes"],capture_output=True,text=True).stdout.split("\n")
    f=[x for x in f if x.endswith(".cpp") and "/src/" in x]
    if not f: return None,"no ref"
    key=os.path.basename(f[0])[:-4]; cls=f[0].split("/")[2]
    md=glob.glob("work/classes/%s/%s.md"%(cls,key))
    if not md: return None,"no md"
    lines=open(md[0]).read().splitlines(); addrs=[]
    for i,ln in enumerate(lines):
        g=re.search(r'([0-9a-f]+):\s*ldr\s+\w+,\[0x([0-9a-f]+)\]',ln)
        if g and i+1<len(lines) and re.search(r'add\s+\w+,\s*pc',lines[i+1]):
            add_ghidra=int(re.match(r'\s*([0-9a-f]+):',lines[i+1]).group(1),16)
            pool_elf=int(g.group(2),16)-0x10000; off=int.from_bytes(rd(pool_elf,4),"little")
            t=(add_ghidra-0x10000+4)+off
            if RODATA[0]<=t<RODATA[1] or DATA[0]<=t<DATA[1]: addrs.append(t)
    addrs=sorted(set(a for a in addrs if a%4==0))   # tables are word-aligned; drop misresolutions
    if len(addrs)==1: return addrs[0],"ok"
    return None,("ambiguous(%d)"%len(addrs) if addrs else "no .rodata ref")

emit=[]; report=[]
for stub in sorted(set(CANDIDATES)):
    d=decl_of(stub)
    if not d: report.append((stub,"no decl","")); continue
    ctype,cnt,ptr=d; esz=SZ.get(ctype,4)
    addr,why=ref_addr(stub)
    if addr is None: report.append((stub,why,"%s%s"%(ctype,"*"if ptr else ""))); continue
    n=cnt or 16                                   # unsized: grab 16 elems (generous; const=safe)
    raw=rd(addr,n*esz)
    def val(i):
        b=raw[i*esz:(i+1)*esz]
        if ctype=="float":
            import struct; return "%.9gf"%struct.unpack("<f",b)[0]
        return str(int.from_bytes(b,"little"))
    vals=", ".join(val(i) for i in range(n))
    emit.append((stub,ctype,cnt,ptr,vals,addr))
    report.append((stub,"0x%x"%addr,"%s%s[%s]"%(ctype,"*"if ptr else "",cnt if cnt else "~%d"%n)))

os.makedirs("work/runtime",exist_ok=True)
with open("work/runtime/consts.cpp","w") as o:
    o.write("// AUTO-GENERATED by work/gen_consts.py — real values for const data-table stubs,\n")
    o.write("// extracted from the target's .rodata/.data. Overrides the zeroed weak stubs.\n")
    o.write("#include <stdint.h>\n\n")
    for stub,ctype,cnt,ptr,vals,addr in emit:
        if ptr:
            o.write('extern "C" %s* %s;\n'%(ctype,stub))
            o.write("static const %s _d_%s[] = { %s };\n"%(ctype,stub,vals))
            o.write("%s* %s = (%s*)_d_%s;\n\n"%(ctype,stub,ctype,stub))
        else:
            dim=str(cnt) if cnt else ""
            o.write('extern "C" %s %s[%s];\n'%(ctype,stub,dim))
            o.write("%s %s[%s] = { %s };\n\n"%(ctype,stub,dim,vals))

print("=== const-table recovery ===")
for s,a,b in sorted(report): print("  %-34s %-14s %s"%(s,a,b))
print("\nrecovered %d/%d tables -> work/runtime/consts.cpp"%(len(emit),len(report)))
